apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: ops-pipeline
spec:
  steps:
  - name: model
    model: ops-model
  - name: xgb
    model: ops-xgb
  - name: combine
    container:
      image: mipjeiger/ops-combiner:latest