apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: marketing-model
spec:
  predictors:
    - name: default
      replicas: 1
      graph:
        name: marketing-model
        children: []
      componentSpecs:
        - spec:
            containers:
              - name: marketing-model
                image: mipjeiger/marketing-model:latest
                imagePullPolicy: Always