apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: seldon-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin123
  AWS_SECRET_ACCESS_KEY: supersecure123
  AWS_ENDPOINT_URL: http://minio.seldon-system-v2:9000