apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: fraud-model
spec:
  annotations:
    seldon.io/executor-image: "seldonio/seldon-core-executor:1.18.0"
  predictors:
    - name: default
      replicas: 1
      graph:
        name: fraud-model
        type: MODEL
        children: []          
      componentSpecs:
        - spec:
            containers:
              - name: fraud-model
                image: mipjeiger/fraud-model:latest
                imagePullPolicy: IfNotPresent
                env:
                  - name: MODEL_NAME
                    value: FraudModel
                  - name: SERVICE_TYPE
                    value: MODEL
                resources:
                  requests:
                    cpu: "0.5"
                    memory: "512Mi"
                  limits:
                    cpu: "1"
                    memory: "1Gi"